export enum LogType {
  ARCHIVED = 0,
  CREATED = 1,
  REMOVED = 2,
  UPDATED = 3,
  RESPONSIBLE_ASSIGNMENT = 6
}

export enum OpportunityLog {
  ANNOTATION_CREATED = 8,
  ANNOTATION_DELETED = 12,
  ANNOTATION_UPDATED = 11,
  ARCHIVED = 4,
  CHANGED = 5,
  CREATED = 1,
  MOVED = 2,
  REMOVED = 3,
  RESPONSIBLE_ASSIGNMENT = 6,
  STATUS_CHANGED = 7
}
